theme: jekyll-theme-minimal
markdown: kramdown
title: Proyecto de Biodiseño 1
description: Página oficial del curso "Proyecto de Biodiseño 1" (C1129) del programa de Ingeniería Biomédica PUCP-UPCH
show_downloads: true
